### ISSUE TITLE
Did you drop this project?

### ISSUE THREAD

**Issue by edo0xff** [Thesola10/PictoChat#6]
I think it's an interesting project. I wanted to connect pictochat with discord too so doing some research I found your project and I'm wondering why you droped it. Anyways, I'll get a 2nd DS in a couple days to start sniffing pictochat messages and find out how they works.

Cheers!

**Comment by Thesola10** [comment]
I appreciate any help, I'm currently a CS student and can't really find time for this project. Also, see #1 for why I couldn't really start much.

**Comment by edo0xff** [comment]
Oh I see. Well I hope I can find something interesting and if I do I'll share it with you. Actually I already did some sniffing and I could capture some packets from the DS but they doesn't tell me anything so I guess I need a second DS to see the messages beeing sended between them.

**Comment by BitterSweetcandyshop** [comment]
2022 now.. damn, any was working on a pictochat rice, imma guess this is offically dead, I'm gonna learn C and am getting a package sniffer soon (muarader mini)

Is anyone even interested this anymore bc I find this cool and would sick with my linux rice:
my project idea atm:
make my raspi/arch laptop handle pictochat text
run that text as a command and trigger home automation tasks
soley for the point it would be hilarious to not use siri and us pictochat on an old ds instead

**Comment by Thesola10** [comment]
@BitterSweetcandyshop you get me :D 

Turns out getting a prism54 radio is harder than I thought, I had intended to use PictoSniff as a starting point but you're free to try (and hopefully PR) a different approach

**Comment by MrPresidentWhite** [comment]
I would like to make a online plattform out of this just for fun but i don’t have ans experiences with reverseengeeniering things. I would appreciate if this project or something similar would go on.

**Comment by techchrism** [comment]
Something I'm interested in (not sure if it's even possible with the hardware) is getting pictochat to interface with an esp8266/esp32 board

**Comment by GFORCEIAN** [comment]
I think this is an awesome project. im currently at university for Computer engineering but id love to sink some hours into this during the summer. Main goal would be to chat between pc and dsi. then discord down the line. also home automation with this sounds so funny and cool
